[application]
name = "SKILL"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "SKILL - Skill-Based Mining"

[web.watcher]
watch_path = ["src", "public"]
reload_html = true
index_on_404 = true

[application.devtools]
open_debugger = false

[web.resource]
style = ["/tailwind.css"]

[web.resource.dev]
style = ["/tailwind.css"]

[[web.proxy]]
backend = "https://api.devnet.solana.com/rpc"

[bundle]
identifier = "skill.mine"
icon = ["public/icon.png"]
